# Generated by Django 4.2.5 on 2023-10-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
